config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'users#index'
  resources :project_users  
  resources :projects  do
    resources :tickets, except: [:index, :show]
  
end
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  mount Sidekiq::Web => '/sidekiq'
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tickets , dependent: :destroy
    has_many :project_users 
    has_many :users, through: :project_users , dependent: :destroy 
    
    after_save :project_created
     
    def project_created
        self.users.each do |user|
            ProjectmailerMailer.with(project: self, user: user).project_created.deliver_now
        end
    end
    scope :by_users, lambda {|current_user|(left_joins(:project_users).where(project_users: {user_id: current_user}))
                        .or(left_joins(:project_users).where(projects: {user_id: current_user})).distinct}
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  enum status: {
    ToDo: 0,
    InProgress: 1,
    Done: 2
  }
  has_one_attached :avatar
  
  after_save :perform

  def perform
    if Date.today == self.end && (status != 2)
      project.users.each do |user|

        TicketEndJob.set(wait_until: self.end.to_time).perform_later(self, project ,user )
      
    end
  end 
end
end 

app/models/user.rb
class User < ApplicationRecord
  has_many :project_users
  has_many :projects, through: :project_users 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
after_create :welcome
  def welcome
    UserMailer.with(user: @user).welcome.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/project_users_controller.rb
class ProjectUsersController < ApplicationController

   def index
     @project_users = ProjectUser.all
   end
   
   def show 
    binding.pry
    #   @project_user = ProjectUser.find(current_user.id)
   end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin
      @projects = Project.all
    # else
    #   @project_owner = Project.where(:user_id => current_user.id)
    #   @project_adds  = current_user.projects
    #   @projects = (@project_owner + @project_adds)
    # end
    else 

    @projects = Project.by_users(current_user.id)
   
    #  @projects = Project.find_by_sql("
    #   SELECT DISTINCT projects.* FROM projects
    #   LEFT JOIN project_users ON project_users.project_id = projects.id
    #   where ( projects.user_id = #{current_user.id} OR project_users.user_id = #{current_user.id})")
    end  
      @project = Project.new
  end
  def show
    if current_user.admin
      @project = Project.find(params[:id])
    else
      @project = Project.by_users(current_user.id).find(params[:id])
    end
  end  
  def new
    @project = current_user.projects.new
  end    

  def edit
    if current_user.admin
      @project = Project.find(params[:id])
    elsif (@project.user_id == current_user.id)
      @project = Project.by_users(current_user.id).find(params[:id])
    end
  end
  def create
    @project = current_user.projects.new(project_params)
    @project.user_id = current_user.id
    if @project.save
        redirect_to  projects_path(@project), notice: 'Project was successfully created.'
    else
        redirect_to new_project_path status: :unprocessable_entity
    end  
  end
  def update
    if current_user.admin
      if @project.update(project_params)
        redirect_to projects_path(@project), notice: 'Project was successfully updated.'
      end
    elsif  
      (@project.user_id == current_user.id)
      @project = Project.by_users(current_user.id).find(params[:id])
      if @project.update(project_params)
        redirect_to projects_path(@project), notice: 'Project was successfully updated.'
      else
        redirect_to new_project_path status: :unprocessable_entity
      end
    end
  end 
  def destroy
    if current_user.admin
      @project.destroy
      redirect_to root_path, notice: 'Project was successfully destroyed.'
    elsif
      (@project.user_id == current_user.id)
      @project.destroy
      redirect_to root_path, notice: 'Project was successfully destroyed.'
    end  
  end

private
  
  def set_project
    @project = Project.find(params[:id])
  end
  def project_params
    params.require(:project).permit(:project_id, :name , :title , :start , :end , user_ids:[])
  end    
end 

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_ticket, only: %i( show update edit  destroy)

  def index
    @tickets = Ticket.all
  end
  def show
    @ticket = tickets.find(params[:id])
  end  
  def edit
    @ticket = @project.tickets.find(params[:id])
  end
  def new 
    @ticket = @project.tickets.new
  end 
  def create
    @ticket = @project.tickets.new(ticket_params) 
    if @ticket.save
      redirect_to project_path(@project), notice: 'Ticket was successfully created.'
    else
      redirect_to new_project_path , status: :unprocessable_entity 
    end
  end 
  def update
    if @ticket.update(ticket_params)
      redirect_to project_path(@project), notice: 'Ticket was successfully update.'
    else
      redirect_to new_project_path , status: :unprocessable_entity
    end 
  end 
  def destroy
    @ticket.destroy
    redirect_to project_ticket_path, notice: 'Ticket was successfully deleted.'
  end 
private  
  def set_project
    @project = (Project.left_joins(:project_users).where(project_users: {user_id: current_user.id})
    .or(Project.left_joins(:project_users).where(projects: {user_id: current_user.id}))).distinct
    .find(params[:project_id])
  end
  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end
  def ticket_params
    params.require(:ticket).permit(:name, :title, :content, :status, :start, :end, :avatar)
  end  
end   

app/controllers/users.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
    end 
    def edit
        @user = User.find(params[:id])
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

   def index
      @users = User.all
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
      end
    
      def resource
        @resource ||= User.new
      end
    
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

app/helpers/project_users_helper.rb
module ProjectUsersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">    </link>
  <script src="https://cdn.tailwindcss.com"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <style>
    .navbar-nav {
        margin-left: auto;
    }
  </style>
</head>
<body>
  <%= render 'shared/navbar'%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/project_users/index.html.erb
<h1>end</h1>
<% @project_users.each do |f| %>
<%= f.user_id%><br>
<%= f.project_id%><br>
<%end%>

app/views/project_users/show.html.erb
<h1>show</h1>

app/views/projects/_form.html.erb
<div>
  <h1 class="font-bold text-4xl">Projects</h1>
</div>
<!--
  UI Design Prototype
  Link : https://dribbble.com/shots/10452538-React-UI-Components
-->
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">i</div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <h2 class="leading-relaxed">Create a Project</h2>
          </div>
        </div>
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
            <%= simple_form_for (@project) do |f| %>
              <%= f.error_notification %>
              <div class="flex flex-col">
                <%= f.input :name , autofocus: true, :input_html => { :class => 'px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600' } , placeholder:"Event title"%>
              </div>
              <div class="flex flex-col">
                <%= f.input :title , :input_html =>{:class=>"px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"}, placeholder:"Event title"%>
              </div>
              <div class="flex items-center space-x-4">
                <div class="flex flex-col">
                  <div class="relative focus-within:text-gray-600 text-gray-400">
                    <%= f.input :start ,:input_html=>{:class=>"pr-4 pl-10 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600" },placeholder:"25/02/2020"%>
                  </div>
                </div>
                <div class="flex flex-col">
                  <div class="relative focus-within:text-gray-600 text-gray-400">
                    <%=f.input :end, :input_html=>{:class=>"pr-4 pl-10 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"}, placeholder:"26/02/2020"%>
                  </div>
                </div>
              </div>
              <div class="mb-2"  style="
                    overflow-y: scroll;
                      height: 100px">
                      <%= f.collection_check_boxes(:user_ids, User.without(current_user), :id,:email)%>
              </div>
              <div class="pt-4 flex items-center space-x-4">
                <%= link_to 'cancel', root_path, class:"bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
                <%= f.button :submit ,class:"bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/projects/edit.html.erb
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">i</div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <h2 class="leading-relaxed">Create a Project</h2>
            </div>
        </div>
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
             <%= simple_form_for @project, url: project_path(@project) do |f| %>
              <%= f.error_notification %>

            <div class="flex flex-col">
               <%= f.input :name , autofocus: true, :input_html => { :class => 'px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600' } , placeholder:"Event title"%>
            </div>
            <div class="flex flex-col">
               <%= f.input :title , :input_html =>{:class=>"px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"}, placeholder:"Event title"%>
            </div>



            <div class="flex items-center space-x-4">
              <div class="flex flex-col">
                <div class="relative focus-within:text-gray-600 text-gray-400">
                  <%= f.input :start ,:input_html=>{:class=>"pr-4 pl-10 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600" },placeholder:"25/02/2020"%>
                 </div>
              </div>
              <div class="flex flex-col">
                <div class="relative focus-within:text-gray-600 text-gray-400">
                  <%=f.input :end, :input_html=>{:class=>"pr-4 pl-10 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"}, placeholder:"26/02/2020"%>
                  
                </div>
              </div>
            </div>
            <div class="mb-2" style="
                    overflow-y: scroll;
                      height: 100px">
              <%= f.collection_check_boxes(:user_ids, User.without(current_user), :id,:email)%>
            </div>
          <div class="pt-4 flex items-center space-x-4">
               <%= link_to 'cancel', root_path, class:"bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
              <%= f.button :submit ,class:"bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>

          </div>
           <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render "projects/form", project: @project%>

app/views/projects/show.html.erb
<section class="bg-black ">
  <div class="container px-5 py-12 mx-auto lg:px-20">
    <div class="flex flex-col flex-wrap pb-6 mb-12 text-white ">
      <h1 class="mb-12 text-3xl font-medium text-white">
        <%=@project.name%>
      </h1>
  <%=@project.user_id %><br><br>
      <% @project.users.each do |u|%>
      <li><%= u.email%></li>
      <% end %><br><br>
      <p class="text-base leading-relaxed">
        <%=@project.title%>
      </div>
      <p class="flex items-center mb-2 text-lg font-normal tracking-wide text-white">
        <span
                        class="inline-flex items-center justify-center flex-shrink-0 w-5 h-5 mr-2 text-white rounded-full bg-blue-1300">
          <svg fill="none" stroke="currentColor" stroke-linecap="round"
                         stroke-linejoin="round" stroke-width="2.5" class="w-4 h-4" viewBox="0 0 24 24">
          </svg>
        </span><%=@project.start%>
      </p>
      <p class="flex items-center mb-2 text-lg font-normal tracking-wide text-white">
        <span
                        class="inline-flex items-center justify-center flex-shrink-0 w-5 h-5 mr-2 text-white rounded-full bg-blue-1300">
          <svg fill="none" stroke="currentColor" stroke-linecap="round"
                         stroke-linejoin="round" stroke-width="2.5" class="w-4 h-4" viewBox="0 0 24 24">
          </svg>
        </span><%=@project.end%>
      </p>
      <div class="w-full xl:w-1/4 md:w-1/4 lg:ml-auto">
          <div class="relative flex flex-col h-full p-8">
            
            <button
                 class="w-full px-4 py-2 mx-auto mt-3 text-white transition duration-500 ease-in-out transform border border-gray-900 rounded-lg text-md hover:bg-gray-900 focus:shadow-outline focus:outline-none focus:ring-2 ring-offset-current ring-offset-2 focus:border-gray-700 focus:bg-gray-800 ">
                  <%= link_to "update project", [:edit, @project]%>
            </button>
            <button
                 class="w-full px-4 py-2 mx-auto mt-3 text-white transition duration-500 ease-in-out transform border border-gray-900 rounded-lg text-md hover:bg-gray-900 focus:shadow-outline focus:outline-none focus:ring-2 ring-offset-current ring-offset-2 focus:border-gray-700 focus:bg-gray-800 ">
                  <%= link_to "New Ticket", new_project_ticket_path(@project)%>
            </button>

            
          </div>
        </div>
     
     <%- @project.tickets.each do |ticket|%>
      <div
                    class="flex flex-wrap items-end justify-start w-full transition duration-500 ease-in-out transform bg-black border-2 border-gray-600 rounded-lg hover:border-white ">
        <div class="w-full xl:w-1/4 md:w-1/4">
          <div class="relative flex flex-col h-full p-8 ">
            <h2 class="mb-4 font-semibold tracking-widest text-white uppercase title-font">
              <%= ticket.name%><br>
              <%= ticket.start%><br>
              <%= ticket.end%>
            </h2>
            <p class="flex items-center mb-2 text-lg font-normal tracking-wide text-white">
              <span
                                    class="inline-flex items-center justify-center flex-shrink-0 w-5 h-5 mr-2 text-white rounded-full bg-blue-1300">
                <svg fill="none" stroke="currentColor" stroke-linecap="round"
                                        stroke-linejoin="round" stroke-width="2.5" class="w-4 h-4" viewBox="0 0 24 24">
                </svg>
              </span><%= ticket.title%>
            </p>
            <p class="flex items-center mb-2 text-lg font-normal tracking-wide text-white">
              <span
                                    class="inline-flex items-center justify-center flex-shrink-0 w-5 h-5 mr-2 text-white rounded-full bg-blue-1300">
                <svg fill="none" stroke="currentColor" stroke-linecap="round"
                                        stroke-linejoin="round" stroke-width="2.5" class="w-4 h-4" viewBox="0 0 24 24">
                </svg>
              </span>
            </p>
            <p class="flex items-center mb-2 text-lg font-normal tracking-wide text-white">
              <span
                                    class="inline-flex items-center justify-center flex-shrink-0 w-5 h-5 mr-2 text-white rounded-full bg-blue-1300">
                <svg fill="none" stroke="currentColor" stroke-linecap="round"
                                        stroke-linejoin="round" stroke-width="2.5" class="w-4 h-4" viewBox="0 0 24 24">
                </svg>
              </span>
            </p>
          </div>
        </div>
        <div class="w-full xl:w-1/4 md:w-1/4">
          <div class="relative flex flex-col h-full p-8 ">
            <p class="flex items-center mb-4 text-lg font-normal tracking-wide text-gray-100">
             <%= ticket.content%>
            </p>
          </div>
        </div>
        <div class="w-full xl:w-1/4 md:w-1/4">
          <div class="relative flex flex-col h-full p-8 ">
            <p class="flex items-center mb-4 text-lg font-normal tracking-wide text-gray-100">
              <% if ticket.avatar.attached?%>
              <%= image_tag ticket.avatar, width: "100%" %>
              <%end %>
            </p>
          </div>
        </div>

        <div class="w-full xl:w-1/4 md:w-1/4 lg:ml-auto">
          <div class="relative flex flex-col h-full p-8">
            <button class="bg-blue-500 rounded-lg font-bold text-white text-center px-4 py-1 transition duration-300 ease-in-out hover:bg-blue-600 mr-2">
              <%= ticket.status%>
            
            </button>
            <button
                                class="w-full px-4 py-2 mx-auto mt-3 text-white transition duration-500 ease-in-out transform border border-gray-900 rounded-lg text-md hover:bg-gray-900 focus:shadow-outline focus:outline-none focus:ring-2 ring-offset-current ring-offset-2 focus:border-gray-700 focus:bg-gray-800 ">
              <%= link_to "Delete", project_ticket_path(@project,ticket) , data: {
                                                                                             turbo_method: :delete,
                                                                                             turbo_confirm: "Are you sure?" }    %>
            </button>
            <button
                                class="w-full px-4 py-2 mx-auto mt-3 text-white transition duration-500 ease-in-out transform border border-gray-900 rounded-lg text-md hover:bg-gray-900 focus:shadow-outline focus:outline-none focus:ring-2 ring-offset-current ring-offset-2 focus:border-gray-700 focus:bg-gray-800 ">
              <%= link_to "Edit Ticket", [:edit, @project, ticket]%>                  
            </button>
          </div>
        </div>
        
    </div><br>
 <% end %>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="bg-blue-400 border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <%= link_to 'Home bage', root_path, class: "self-center text-xl font-semibold whitespace-nowrap dark:text-white"%>
    <button data-collapse-toggle="mobile-menu" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
      <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <% if user_signed_in?%>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"%>
        </li>
        <% else %>
        <li>
        <%= link_to 'Sign in', new_user_session_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"%>
        </li>
        <li>
        <%= link_to 'Sign up', new_user_registration_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tickets/_form.html.erb
<div>
  <h1 class="font-bold text-4xl">Tickets</h1>
</div>
<!--
  UI Design Prototype
  Link : https://dribbble.com/shots/10452538-React-UI-Components
-->
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">i</div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <h2 class="leading-relaxed">Create a Ticket</h2>
            </div>
        </div>
       
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">

             <%= form_with(model: ticket, url: project_tickets_path)  do |f| %>
               
               <%= f.hidden_field :project_id %>

            <div class="flex flex-col">
               <%= f.text_field :name , autofocus: true,:class => 'px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600'  , placeholder:"Ticket name"%>
            </div><br>
            <div class="flex flex-col">
               <%= f.text_field :title ,autofocus: true,:class=>'px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600', placeholder:"Ticket title"%>
            </div><br>
            <div class="flex flex-col">
               <%= f.text_area :content ,autofocus: true,:class=>'px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600', placeholder:"Ticket content"%>
            </div><br>
            <div class="flex items-center space-x-4">
              <div class="flex flex-col">
                <div class="relative focus-within:text-gray-600 text-gray-400">
                  <%= f.date_select :start ,:class=>"pr-4 pl-10 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600" ,placeholder:"25/02/2020"%>
                 </div>
              </div>
              <div class="flex flex-col">
                <div class="relative focus-within:text-gray-600 text-gray-400">
                  <%=f.date_select :end,:class=>"pr-4 pl-10 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600", placeholder:"26/02/2020"%>
                  
                </div>
              </div>
            </div>
                  <%= f.label :status %>
                  <%= f.select :status, options_for_select(Ticket.statuses.map {|key, value| [key.titleize, Ticket.statuses.key(value)]}, @ticket.status) %>
             <div class="flex flex-col">
                <%= f.file_field :avatar %>
              </div>  
          <div class="pt-4 flex items-center space-x-4">
               <%= link_to 'cancel', root_path, class:"bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
              <%= f.submit "Create",:class=>"bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
          
          </div>
           <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
          

app/views/tickets/new.html.erb
<%= render "tickets/form", ticket: @ticket%>